### ISSUE TITLE
Push missing

### ISSUE THREAD

**Issue by rubydesign** [seattlerb/wilson#3]
wilson/operand.rb:24:in `method_missing': undefined method`push' for #Wilson::Register:0x007fe1ba829c88 (NoMethodError)

I have pulled each class into it's own file, see here https://github.com/crystal-ruby/wilson/
The offending push is on Object assemble (last line below)

class Object
  def assemble arg_count = 0, &block
    asm = Wilson::MachineCodeX86.new

```
# TODO: enter?
asm.ebp.push
```

BTW: Requirements could state ruby version. I get core dumps with 1.8.7 (as the other issue mentions i guess) and have thus changed to fiddle using 2.0

Still, shame it doesn't work

**Comment by zenspider** [comment]
Is this code still available somewhere?

**Comment by zenspider** [comment]
(specifically, your crystal-ruby link above is dead)

**Comment by dancinglightning** [comment]
yes, had to rename because there was another crystal. 
So instead of crystal-ruby it's now salama.

**Comment by dancinglightning** [comment]
Hmm, i just looked at my repo https://github.com/salama/salama-intel

and noticed that i changed the name and at least the top level module (to Intel) and to be honest i don't remember what else. Though i believe not much.

Don't know if you remember, but i am writing a ruby vm entirely in ruby. 
And time has passed and so i am at least able to generate executables (for linux/arm)

So i copied your code for someone to be able to do an intel backend to salama (the vm).
And maybe, since you put the work into this wilson, you may be interested in being that person to do the integration. There is good abstraction (also of a register machine level) in place, so it should not be soo hard :-)
